version: "3.9"
services:
  plantuml:
    build:
      args:
        ALPINE_VERSION: "3.16.3"
        PLANTUML_SERVER_VERSION: "1.2022.7"
        TOMCAT_VERSION: "10.0.27"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "plantuml:dev"
    image: "plantuml:dev"
    ports:
      - "8080:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/plantuml/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/plantuml/backup-volume
      

