kind: pipeline
type: exec
name: Container Build - PlantUML

platform:
  os: linux
  arch: arm64

steps:
- name: build
  environment:
    ALPINE_VERSION: 3.16.3
    PLANTUML_VERSION: 1.2022.7
    TOMCAT_VERSION: 10.0.27
  commands:
  - podman build --build-arg ALPINE_VERSION=$ALPINE_VERSION --build-arg PLANTUML_VERSION=$PLANTUML_VERSION --build-arg TOMCAT_VERSION=$TOMCAT_VERSION --file Containerfile --format docker --label revision="$(git rev-parse HEAD)" --label version="$(date +%Y.%m.%d)" --no-cache --tag plantuml:build .
- name: publish
  environment:
    CONTAINER_NAME: "plantuml"
    PLANTUML_VERSION: 1.2022.7
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
  commands:
   - podman tag $CONTAINER_NAME:build docker.io/$DOCKERIO_USERNAME/$CONTAINER_NAME:$PLANTUML_VERSION
   - podman login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD docker.io
   - podman push docker.io/$DOCKERIO_USERNAME/$CONTAINER_NAME:$PLANTUML_VERSION
   - podman push docker.io/$DOCKERIO_USERNAME/$CONTAINER_NAME:latest

trigger:
  branch:
  - main
